services:
  console-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: console-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./api/data:/app/api/data
      - ./api/data/uploads:/app/api/data/uploads
    environment:
      - NODE_ENV=production
      - PUBLIC_DIR=/app/public
      - UPLOADS_DIR=/app/api/data/uploads